VERILOG = ../src/sms.v ../src/ram.v ../src/vram.v ../src/rom.v \
	  ../src/Z80/tv80_core.v ../src/Z80/tv80n.v ../src/Z80/tv80_mcode.v \
	  ../src/Z80/tv80_reg.v ../src/Z80/tv80_alu.v \
	  ../src/video.v ../src/hdmi.v \
	  ../src/sn76489.v ../src/tone_generator.v \
	  ../src/lattice/ecp5pll.sv \
	  ../src/sdram.v \
	  ../src/osd/osd.v ../src/osd/spi_osd.v \
	  ../src/osd/spi_ram_btn.v ../src/osd/spirw_slave_v.v

PIN_DEF = ulx3s_v20.lpf

include ulx3s.mk

